# This file will only contains the implementation. Please note that you also need a file of the same name on the default branch to show up in the UI https://github.com/SAP-samples/sap-tech-bytes/blob/main/.github/workflows/deploy.yaml

name: Deploy Manually

# Triggered manually
on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sap-samples/tech-bytes-kyma-cicd

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: npm install

      - run: npm run build

      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.DEV_KUBECONFIG }}
          command: apply -n tutorial -f ./k8s/dev_deployment.yaml
