name: Run Tests

on:
  push:
    branches:
      - 2021-08-02-github-actions-kyma

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: npm test